### PR TITLE
Enable trustability

### PR DESCRIPTION
**Pull request by Adrion**
re enable trust with new jquery dom creation

### CODE REVIEW

**Comment by Adrion** [comment]
Can someone check this PR please ? :)
There are no major changes but as I enable and old feature with the new DOM creation I prefer the code to be reviewed before merging :)

Many thanks !

**Comment by williambelle** [comment]
The translations should be cleaned

**Comment by williambelle** [comment]
When the score is 0, it's hard to understand trustability...


score-0

**Comment by williambelle** [comment]
The trustability part is not very readable (icon color + margin). I don't know the principles by heart when they are missing...

webmd

Below, a more readable example

more-readable

**Comment by williambelle** [comment]
I'm sad to see that

provisu

It doesn't represent all the work that Aude has done on the content...

**Comment by Adrion** [comment]
I agree with the new design. 
Yes for provisu.ch i'll checkout if we already index some content in the new index.

**Pull request merged**
